import Head from "next/head";

import { Header } from "../Layout/Header";
import { SideNavBar } from "../Layout/SideNavBar";
import styled from "styled-components";

const MainContainer = styled.main`
  background: hsl(238, 27%, 12%);
  display: grid;
  grid-template-columns: 225px 1fr;
  grid-template-rows: 1fr;
  width: 100vw;
  height: 100vh;
`;

const MainContentContainer = styled.div`
  display: flex;
  flex-direction: column;
`;

export const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Podbay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <MainContainer>
        <SideNavBar />
        <MainContentContainer>
          <Header />
          {children}
        </MainContentContainer>
      </MainContainer>
    </>
  );
};
